### ISSUE TITLE
Returning 404 in '/people/17'

### ISSUE THREAD

**Issue by MrCesar107** [Juriy/swapi#12]
The API returns a ``404`` status error when requests to endpoint `https://swapi.dev/api/people/17`

**Comment by mlittlec** [comment]
That appears to because there isn't any record with the id of 17 (checkout the "pk" field) in the people.json file located here: 

[https://github.com/phalt/swapi/blob/master/resources/fixtures/people.json](https://github.com/phalt/swapi/blob/master/resources/fixtures/people.json)

Snippet below shows there is nothing to be returned from the URL: [https://swapi.dev/api/people/17](https://swapi.dev/api/people/17)

{
    "fields": {
        "edited": "2014-12-20T21:17:50.338Z",
        "name": "Jabba Desilijic Tiure",
        "created": "2014-12-10T17:11:31.638Z",
        "gender": "hermaphrodite",
        "skin_color": "green-tan, brown",
        "hair_color": "n/a",
        "height": "175",
        "eye_color": "orange",
        "mass": "1,358",
        "homeworld": 24,
        "birth_year": "600BBY"
    },
    "model": "resources.people",
    "pk": 16
},
{
    "fields": {
        "edited": "2014-12-20T21:17:50.341Z",
        "name": "Wedge Antilles",
        "created": "2014-12-12T11:08:06.469Z",
        "gender": "male",
        "skin_color": "fair",
        "hair_color": "brown",
        "height": "170",
        "eye_color": "hazel",
        "mass": "77",
        "homeworld": 22,
        "birth_year": "21BBY"
    },
    "model": "resources.people",
    "pk": 18
},

**Comment by Juriy** [comment]
Generally speaking for APIs it is perfectly normal to have 404s for some IDs: clients should not rely that every ID in a sequence has an entity attached to it. Moreover most modern APIs discourage the use of numeric IDs (generating pseudorandom strings instead), which makes iteration impossible.
