### ISSUE TITLE
Id missing on the resources

### ISSUE THREAD

**Issue by Gio85** [Juriy/swapi#28]
Hi @Juriy,
I just wanted to check if there is any way to get the id from each resource.
Otherwise will be quite hard try to get a single resource.
Thanks

**Comment by hector4213** [comment]
Hey, good question! First of all, I'm here to see if this was an issue for anyone else. I encountered this problem myself. But if you take a look at the data, the "id" is provided in the URL property of the character response. So I made a helper function to extract the number from the URL property with regex. it was a problem for me because React cries if no keys are provided and I wanted to do the same thing, fetch resources by a unique identifier. Hope it helps!

**Comment by Juriy** [comment]
Thanks for your feedback! Right now I'm working over a set of API improvements and having IDs is one of the open points. I wouldn't want to change an existing API shape (even in backwards compatible way) since there are plenty resources and tutorials that rely on it. I'd rater introduce a completely new API version that would incorporate those changes.
